### ISSUE TITLE
Install PHP extensions from `.platform.app.yaml`

### ISSUE THREAD

**Issue by lolautruche** [platformsh/ddev-platformsh#23]
PHP extensions can be [declared in the `.platform.app.yaml`](https://docs.platform.sh/languages/php/extensions.html):

```yaml
runtime:
    extensions:
        - blackfire
        - http
        - igbinary
        - redis
    disabled_extensions:
        - sqlite3
```

This should be reflected in DDEV.
