### ISSUE TITLE
Improper mapping of relationships - blog.blackfire.io database for example

### ISSUE THREAD

**Issue by rfay** [platformsh/ddev-platformsh#38]
Testing out blog.blackfire.io I see that `config.platformsh.yaml` ends up with 
```yaml
database:
  type: mysql
  version: 10.2
```
which is obviously impossible, so the mapping here isn't being done right. 
.platform.app.yaml has
```yaml
relationships:
    database: "mysqldb:mysql"
    cache: "memcached:memcached"
```
and services.yaml has 
```
mysqldb:
    type: mysql:10.2
    disk: 2048
```

That should work. In relationships lines, the left part of the pair (mysqldb) in this case is free form and should be joined to the item of the same name in services.yaml

**Comment by rfay** [comment]
@lolautruche so in 

```yaml
relationships:
    database: "mysqldb:mysql"
    cache: "memcached:memcached"
```

the right-hand side of `mysqldb:mysql` or `memcached:memcached` is meaningless right? So all we care about, for example, with the `database` line here in .platform.app.yaml is the join value (`mysqldb`, which joins to the services .yaml stanza) and the right-hand side `mysql` is meaningless?
