### ISSUE TITLE
Service key in `$PLATFORM_RELATIONSHIPS` must match service name in `.platform.app.yaml`

### ISSUE THREAD

**Issue by lolautruche** [platformsh/ddev-platformsh#57]
The current scripts that generate the JSON content for `$PLATFORM_RELATIONSHIPS` currently has an arbitrary fixed key (e.g., [`database` for DB](https://github.com/platformsh/ddev-platformsh/blob/main/platformsh/generate_db_relationship.sh#L32), [`essearch` for Elastic Search](https://github.com/platformsh/ddev-platformsh/blob/main/platformsh/generate_elasticsearch_relationship.sh#L6), etc.

The value for this key must actually match the name of the relationship that is defined in `.platform.app.yaml` ([example in Bigfoot app](https://github.com/blackfireio/bigfoot/blob/workshop/.platform.app.yaml#L44-L49)):

```yaml
# .platform.app.yaml

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"
    cache: "memcached:memcached"
```

In the example above, the value to take into account is the relationship key (`database`, `cache`).
