### ISSUE TITLE
Don't run build and deploy hooks on every start

### ISSUE THREAD

**Issue by aimfeld** [platformsh/ddev-platformsh#61]
The plugin creates `post-start` commands to run the platform.sh build and deploy hooks. These commands are run on every `ddev start`. However, I only want to run the build and deploy hooks when I first install the project, not every time I start the project.

I'm migrating from lando, where we had `lando rebuild` (runs the hooks) vs `lando start` (only starts containers). Can you point me to any resources how to achieve the same separation with DDEV?

This is the hooks section created by the plugin:
```yaml
hooks:
  post-start:
    - exec: platform self:update -qy --no-major || true
    - exec: '[ ! -z "${PLATFORMSH_CLI_TOKEN:-}" ] && (platform ssh-cert:load  -y || true)'
    - composer: install
    # platformsh build hooks
    - exec: |
        bin/build-hook
    # platformsh deploy hooks
    - exec: |
        bin/deploy-hook
```
